DELIVERIES = [
    "tablet",
    "capsule",
    "syrup",
    "powder",
    "cream",
    "ointment",
    "bandage",
    "spray",
    "drops",
    "inhaler",
]

CATEGORIES = [
    "analgesic",
    "antacid",
    "anti-biotic",
    "anti-histamine",
    "anti-inflammatory",
    "anti-pyretic",
    "anti-septic",
    "anti-viral",
    "decongestant",
    "expectorant",
    "hormone",
    "immunosuppressant",
    "laxative",
    "mucolytic",
    "stimulant",
    "vasoconstrictor",
]
