include:
  - "api/compose.yml"

services:
  db:
    image: docker.io/postgres:13.10-alpine
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
    env_file:
      - db/.env
    expose:
      - "5432"
    ports:
      - "50454:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
